name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 

on:
  push:
    branches:
      - dev


jobs:
  Ansible install:
  runs-on: ubuntu-latest
  steps:
  - name: Install Ansible
    run: sudo apt-get update && sudo apt-get install ansible -y
 
  Terraform-EC2-Provision:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Step 3: Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform  
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

      # Step 4: Apply Terraform to provision EC2
      - name: Terraform Apply
        run: |
          terraform validate
          terraform apply -auto-approve
        working-directory: ./terraform
          
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

# New Work
      # - name: Install Ansible
      #   run: sudo apt-get update && sudo apt-get install ansible -y

      # - name: Run Ansible Playbook
      #   run: ansible-playbook -i ../ansible/inventory.ini ../ansible/docker_playbook.yml
      #   env:
      #     ANSIBLE_HOST_KEY_CHECKING: "False"